# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: dec16579f6012cd2f628839606d506370ff28e9ef805164973479a3e509a4f1787a7e1272610d97e58959fb766438f5959adb6651a1da3a7edabd56fde6e128d

test:
  secret_key_base: 638db08bedd9b06c642554bb717c83252659177df09b0bcb9941ed3c5264e2961897bba50960710e7647b956f62628f268c591b2ef74568a708953cc8dc7fa68

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
